Repository sodafoundation/documentation, pull requests merged in 2020-09, with the labels that each got.

#99 Added Table of Contents to the Readme
  README.md
Labels: enhancement

#96 Fixed #95. Updated Footer links. Added social icons to menu footer.
  layouts/partials/menu-footer.html
  layouts/partials/menu.html
  static/css/theme-opensds.css
Labels: enhancement

#100 Add EmbedPDF shortcode to embed pdfs
  content/api-specs/_index.md
  layouts/shortcodes/embed-pdf.html
Labels: documentation, enhancement

#101 Add multi-cloud user guide
  content/guides/developer-guides/file-share/_index.md
  content/guides/developer-guides/multi-cloud/_index.md
  content/guides/developer-guides/object-lifecycle-management/_index.md
  content/guides/user-guides/file-share/_index.md
  content/guides/user-guides/object-lifecycle-management/_index.md
  content/guides/user-guides/orchestration/_index.md
  content/guides/user-guides/telemetry/_index.md
Labels: documentation

#104 Updated docker instructions for Ubuntu 18.04
  content/soda-gettingstarted/installation-using-ansible.md
Labels: enhancement

#110 Updated instructions to reflect latest stable release version.
  content/soda-gettingstarted/installation-using-ansible.md
Labels: enhancement
