Repository sodafoundation/documentation, pull requests merged in 2021-01, with the labels that each got.

#128 User guide for multi-cloud archival and retrieval and File and Block service
  content/guides/user-guides/multi-cloud/_index.md
  content/guides/user-guides/multi-cloud/file-and-block/_index.md
  content/guides/user-guides/multi-cloud/file-and-block/soda_backend.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_cloud_block_register.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_cloud_fs_list.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_cloud_fs_register.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_cloud_vol_create.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_cloud_volume_list.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_create_fs.png
  content/guides/user-guides/multi-cloud/file-and-block/soda_home.png
  content/guides/user-guides/multi-cloud/object-archival-restore/_index.md
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_archived_object_download.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_archived_object_list.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_backend.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_bucket.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_home.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_object_archival.png
  content/guides/user-guides/multi-cloud/object-archival-restore/soda_object_restore.png
  content/guides/user-guides/multi-cloud/object-lifecycle-management/_index.md
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_backend.PNG
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_bucket.PNG
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_home.PNG
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_lifecycle.PNG
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_lifecycle_config.PNG
  content/guides/user-guides/multi-cloud/object-lifecycle-management/opensds_object.PNG
Labels: user-guide

#127 Added dashboard developer guide documentation
  content/guides/developer-guides/dashboard/_index.md
Labels: documentation

#136 Update SODA Docs baseurl. Fixes broken search
  config.toml
Labels: bug-fix

#138 Updated the theme to match SODA colors.
  static/css/theme-opensds.css
Labels: enhancement
