Repository sodafoundation/documentation, pull requests merged in 2021-03, with the labels that each got.

#142 Updated the netlify version
  config.toml
  netlify.toml
Labels: enhancement

#147 Add CSI PNP supported Driver list and Integration Guide
  .gitignore
  content/guides/integration-guides/_index.md
  content/guides/integration-guides/csi-integration/_index.md
  content/guides/integration-guides/csi-integration/soda-csi-plugin/_index.md
  content/guides/integration-guides/csi-integration/soda-csi-pnp/_index.md
  content/support-matrix/nbp/_index.md
  content/support-matrix/nbp/csi-pnp/_index.md
Labels: Integration Guide, user-guide

#135 Updated the ansible installation instructions. Updated python3.6 steps
  content/soda-gettingstarted/installation-using-ansible.md
Labels: documentation
