Repository sodafoundation/documentation, pull requests merged in 2021-06, with the labels that each got.

#168 Updating delfin support matrix information
  content/support-matrix/delfin/_index.md
Labels: documentation

#170 Add the soda-proxy pre-requisite for trying pnp solution
  content/guides/integration-guides/csi-integration/soda-csi-pnp/_index.md
Labels: documentation

#165 Add documentation for AKSK
  content/guides/user-guides/multi-cloud/aksk/ak-sk-using-api.md
  content/soda-gettingstarted/installation-using-ansible.md
Labels: user-guide

#173 Adding SSP feature user guide
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP.png
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP_Archive.png
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP_Create.png
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP_CreateBucket.png
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP_Restore.png
  content/guides/user-guides/multi-cloud/storage-service-plan/SSP_Upload.png
  content/guides/user-guides/multi-cloud/storage-service-plan/_index.md
  content/guides/user-guides/multi-cloud/storage-service-plan/register-backend-0.png
  content/guides/user-guides/multi-cloud/storage-service-plan/registerBackend.png
  content/guides/user-guides/multi-cloud/storage-service-plan/soda_login_page.png
Labels: user-guide

#176 Updated installation steps with Ansible installer. Added information regarding Ubuntu 16.04 deprecation.
  content/soda-gettingstarted/installation-using-ansible.md
Labels: enhancement

#178 Added the API spec for Jerba release of SODA.
  content/api-specs/isabela/_index.md
  content/api-specs/jerba/_index.md
  content/api-specs/jerba/soda-api.md
  content/api-specs/jerba/soda-delfin.md
  content/api-specs/jerba/soda-multicloud.md
Labels: documentation
